version: '2'

services:
  db:
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: changeme
    restart: always
    image: postgres:9.6
    expose:
      - "5432"
  
  redis:
    restart: always
    image: redis:3.0
    expose:
      - "6379"
  
  app:
    environment:
      DJANGO_SECRET_KEY: passwd
      DATABASE_URL: postgres://admin:passwd@db/nathhorrigan
      CACHE_URL: redis://redis
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - db:db
      - redis:redis
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

